[package]
name = "otap-df-otlp"
description = "OTLP nodes"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
otap-df-engine = { path = "../engine", features = ["testing"] }
otap-df-channel = { path = "../channel" }
tonic = { version = "0.13.1", default-features = false, features = [
    "server",
    "channel",
    "router",
    "transport",
    "codegen",
    "prost",
    "zstd",
    "gzip",
    "deflate",
] }
prost = "0.13.5"
prost-types = "0.13.5"
thiserror.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true
log = "0.4"
hex = "0.4.3"
futures = "0.3.31"

[build-dependencies]
tonic-build = { version = "0.13.1", features = ["cleanup-markdown"] }

thiserror = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }


[dev-dependencies]
portpicker = "0.1.1"