[package]
name = "otap-df-otlp"
description = "OTLP nodes"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
otap-df-engine = { path = "../engine" }
otap-df-channel = { path = "../channel" }
log = "0.4"

# Workspace dependencies
thiserror.workspace = true

[dev-dependencies]
tonic = { version = "0.13.0", default-features = false, features = [
    "server",
    "channel",
    "transport",
    "codegen",
    "prost",
    "zstd",
    "gzip",
    "deflate",
] }
prost = "0.13.4"
serde_json.workspace = true
tokio.workspace = true

[build-dependencies]
tonic-build = { version = "0.13.0", features = ["cleanup-markdown"] }
